image: floragunncom/ci-docker-compose-openjdk11:19.03.1

services:
  - docker:19.03-dind
variables:
  DOCKER_TLS_CERTDIR: "/certs"
before_script:
  - sudo sysctl -w vm.max_map_count=262144
  - docker-compose --version
  - apk update
  - apk add jq curl zip  openssh-client
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh


stages:
  - build

build_oss_images:
  stage: build
  script:
    - echo "Executing $CI_JOB"
    - export ELK_VERSION=$ELK_VERSION
    - export SG_VERSION=$SG_VERSION
    - export SG_KIBANA_VERSION=$SG_KIBANA_VERSION
    - ./docker/build.sh push
  only:
    variables:
      - $CI_JOB == "build_oss"


build_helm_charts:
  image: maven:3.6-jdk-8
  before_script:
    - "echo CI_JOB: $CI_JOB"
    - rm -rf /var/lib/apt/lists/* && apt-get update -yqq && apt-get install -yqq openssh-client apt-utils jq perl libapr1 openssl curl sudo awscli > /dev/null 2>&1
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan git.floragunn.com >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
    - chmod 700 get_helm.sh
    - ./get_helm.sh
  stage: build
  script:
    - |
       #!/bin/bash

       echo "#########################################################"
       echo "Creating Search Guard Helm charts version $CHART_VERSION"
       echo "#########################################################"

       echo "Building package and index file"
       if [ -z "$CHART_VERSION" ];
       then
          echo "WARNING: CHART_VERSION is not set";
       else
          sed -i -e "s#version:.*#version: $CHART_VERSION#g" Chart.yaml
       fi

       helm package ./ -u
       rm -rf charts requirements.lock
       aws s3 cp s3://helm.search-guard.com/index.yaml  ./
       helm repo index ./ --url https://helm.search-guard.com --merge index.yaml

       echo "Uploading Search Guard Helm charts to S3"
       aws s3 cp ./search-guard-helm-*.tgz s3://helm.search-guard.com/
       aws s3 cp ./index.yaml s3://helm.search-guard.com/
       echo "#########################################################"
       echo "Search Guard Helm charts version $CHART_VERSION published to https://helm.search-guard.com"
       echo "#########################################################"
  only:
    variables:
      - $CI_JOB == "build_charts"
