image: maven:3.6-jdk-8


before_script:
  - "echo CI_JOB: $CI_JOB"
  - rm -rf /var/lib/apt/lists/* && apt-get update -yqq && apt-get install -yqq openssh-client apt-utils jq perl libapr1 openssl curl sudo > /dev/null 2>&1
  - pip install awscli --upgrade || true
  - pip3 install awscli --upgrade  || true
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan git.floragunn.com >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts


build_helm_charts:
  stage: build
  script:
    - |
       #!/bin/bash
       DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

       [[ -z "$CHART_VERSION" ]] && { echo "Error: CHART_VERSION is not set" ; exit 1; }
       echo "#########################################################"
       echo "Creating Search Guard Helm charts version $CHART_VERSION"
       echo "#########################################################
       cd $DIR/search-guard-helm
       
       sed -i -e "s#version:.*#version: $CHART_VERSION#g" Chart.yaml
       helm package ./ -u
       rm -rf charts requirements.lock
       aws s3 cp s3://helm.search-guard.com/index.yaml  ./
       helm repo index ./ --url https://helm.search-guard.com --merge index.yaml
       echo "Uploading Search Guard Helm charts to S3"
       aws s3 cp ./search-guard-helm-$CHART_VERSION.tgz s3://helm.search-guard.com/
       aws s3 cp ./index.yaml s3://helm.search-guard.com/
       echo "#########################################################"
       echo "Search Guard Helm charts version $CHART_VERSION published to https://helm.search-guard.com"
       echo "#########################################################"
  only:
    refs:
      - triggers
      - schedules
    variables:
      - $CI_JOB == "build_charts"
