variables:
  BUILDX_VERSION: "0.9.1"
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_CLI_EXPERIMENTAL: "enabled"
  DEBIAN_FRONTEND: noninteractive

stages:
  - build

build_and_push_docker_images:
  allow_failure: false
  stage: build
  image: docker:latest
  services:
  - docker:dind
  tags:
    - test-large
    #needs to run on amd64 because multiarch/qemu-user-static is not
    #available for arm64
  when: manual
  script:
    - apk update
    - apk add bash
    - echo "$DOCKER_PASSWORD" | docker login --username floragunncom --password-stdin docker.io
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - BUILDX_FULL_URL="https://github.com/docker/buildx/releases/download/v${BUILDX_VERSION}/buildx-v${BUILDX_VERSION}.linux-amd64"
    - mkdir -p $HOME/.docker/cli-plugins/
    - wget -O $HOME/.docker/cli-plugins/docker-buildx ${BUILDX_FULL_URL} 
    - chmod a+x $HOME/.docker/cli-plugins/docker-buildx
    - ./docker/build_multiarch.sh