image: floragunncom/ci-docker-compose-openjdk11:19.03.1

services:
  - docker:19.03-dind
variables:
  DOCKER_TLS_CERTDIR: "/certs"
before_script:
  - sudo sysctl -w vm.max_map_count=262144
  - docker-compose --version
  - apk update
  - apk add jq curl zip  openssh-client
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh


stages:
  - build

retry_aws_job:
  stage: build
  script:
    - echo "Executing $CI_JOB"
    - export ELK_VERSION=$ELK_VERSION
    - export SG_VERSION=$SG_VERSION
    - export SG_KIBANA_VERSION=$SG_KIBANA_VERSION
    - ./build.sh push
  only:
    variables:
      - $CI_JOB == "build_oss"
