# Currently tested with Kubernetes 1.15 on Minikube version: v1.11.0
# This example uploads provided single certificate for all ES cluster nodes from ./secrets/nodes/ folder and certificate for sgadmin user from ./secrets/sgadmin/ folder
# and installs 3-nodes ES cluster (master,ingest and data nodes) with one Kibana node
# and exposes es.sg-helm.example.com and kibana.sg-helm.example.com on HTTPS.

# Run this example from search-guard-helm folder by `helm install -f sg-helm/examples/setup_single_elasticsearch_cert/values.yaml sg-elk sg-helm`
# To get access to Kibana:
#  - Run minikube tunnel in different window
#  - Get Kibana external IP by `kubectl get svc|grep LoadBalancer|awk '{print $4}'` and assign it to kibana.sg-helm.example.com in your etc/hosts file
#  - Access https://kibana.sg-helm.example.com with default user kibanaro and password extracted by this command `kubectl get secrets sg-elk-sg-helm-passwd-secret -o jsonpath="{.data.SG_KIBANARO_PWD}" | base64 -d`

common:

  # DN of the admin certificate
  # See https://docs.search-guard.com/latest/sgadmin#configuring-the-admin-certificate
  admin_dn:
    - "CN=sgadmin,OU=Ops,O=Example Com\\, Inc.,DC=example,DC=com"


  # Search Guard needs to securely and reliably identify internal communication between
  # Elasticsearch nodes (inter-node traffic). This communication happens for example if 
  # one node receives a GET request on the HTTP layer, but needs to forward it to another 
  # node that holds the actual data.
  # See https://docs.search-guard.com/latest/tls-in-production#node-certificates


  nodes_dn:
    - "CN=sg,OU=Ops,O=Example Com\\, Inc.,DC=example,DC=com"


  #PKI aprroaches are specified with the following keys:
  #Set sgadmin_certificates_enabled if certificates are self-signed and generated by SG TLS tool
  sgadmin_certificates_enabled: false
  #Set ca_certificates_enabled to true if CA cert and key are copied to ../keys/ca/ folder and used by cluster to generate all certificates for nodes and services
  ca_certificates_enabled: false
  #Set external_ca_certificates_enabled to true if add all certificates for nodes and services to the folder ../keys/nodes/ to use them for encryption
  external_ca_certificates_enabled: false
  #Set external_ca_certificates_enabled to true if add single certificates for all nodes and services to the folder ../keys/sg-esnode/ to use it for encryption
  external_ca_single_certificate_enabled: true
  #Set directory where certificates are stored
  certificates_directory: "examples/setup_single_elasticsearch_cert/secrets"

