{{ if and (not .Values.common.external_ca_certificates_enabled) (not .Values.common.external_ca_single_certificate_enabled) }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "fullname" . }}
    component: sginit
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    sgnodecert: "true"
  name: {{ template "fullname" . }}-nodes-cert-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
{{ end }}
