{{ if (not .Values.common.external_ca_certificates_enabled) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-kibana
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: {{ template "fullname" . }}-kibana
    role: kibana
spec:
  replicas: {{ .Values.kibana.replicas }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      component: {{ template "fullname" . }}
      role: kibana
  template:
    metadata:
      labels:
        release: "{{ .Release.Name }}"
        app: {{ template "fullname" . }}
        component: {{ template "fullname" . }}
        role: kibana
        {{- if .Values.kibana.labels }}
{{ toYaml .Values.kibana.labels | indent 8 }}
        {{- end }}
      annotations:
        {{ if .Values.common.restart_pods_on_config_change }}
        checksum/config: {{ include (print $.Template.BasePath "/kibana-configmap.yaml") . | sha256sum }}
        {{ end }}
      {{- if .Values.kibana.annotations }}
{{ toYaml .Values.kibana.annotations | indent 8 }}
      {{- end }}
    spec:
      subdomain: {{ template "fullname" . }}
      serviceAccountName: {{ template "fullname" . }}
      securityContext:
        fsGroup: 1000
      {{- if eq .Values.kibana.antiAffinity "hard" }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: "topology.kubernetes.io/zone"
              labelSelector:
                matchLabels:
                  component: {{ template "fullname" . }}
                  role: kibana
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  component: {{ template "fullname" . }}
                  role: kibana
      {{- else if eq .Values.kibana.antiAffinity "soft" }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: "topology.kubernetes.io/zone"
              labelSelector:
                matchLabels:
                  component: {{ template "fullname" . }}
                  role: kibana
          - weight: 2
            podAffinityTerm:
              topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  component: {{ template "fullname" . }}
                  role: kibana
      {{- end }}
      initContainers:
        - name: kibana-init
          image: "{{ .Values.common.images.provider }}/{{ .Values.common.images.sgadmin_base_image }}:{{ .Values.common.elkversion }}-{{ .Values.common.sgversion }}"
          imagePullPolicy: {{ .Values.common.pullPolicy }}
          command:
            - sh
            - -c
            - |
                #!/usr/bin/env bash -e
                until kubectl get secrets {{ template "fullname" . }}-passwd-secret; do
                  echo 'Wait for {{ template "fullname" . }}-passwd-secret';
                  sleep 10 ;
                done

                echo "OK, {{ template "fullname" . }}-passwd-secret exists now"

          resources:
            limits:
              cpu: "500m"
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 256Mi
{{ include "generate-certificates-init-container" . | indent 8 }}
      containers:
      - name: kibana
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
              - SYS_RESOURCE
      {{ if .Values.common.xpack_basic }}
        image: "{{ .Values.common.images.provider }}/{{ .Values.common.images.kibana_base_image }}:{{ .Values.common.elkversion }}-{{ .Values.common.sgkibanaversion }}"
      {{ else }}
        image: "{{ .Values.common.images.provider }}/{{ .Values.common.images.kibana_base_image }}:{{ .Values.common.elkversion }}-oss-{{ .Values.common.sgkibanaversion }}"
      {{ end }}
        imagePullPolicy: {{ .Values.common.pullPolicy }}
        lifecycle:
          postStart:
{{ include "remove-demo-certs" . | indent 12 }}
          preStop:
{{ include "lifecycle-cleanup-certs" . | indent 12 }}
        envFrom:
        - secretRef:
            name: {{ template "fullname" . }}-passwd-secret
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: DISCOVERY_SERVICE
          value: {{ template "fullname" . }}-clients.{{ .Release.Namespace }}.svc
        {{- range $key, $value :=  .Values.common.env }}
        - name: {{ $key | upper | replace "-" "_" }}
          value: {{ $value | quote }}
        {{- end }}
        {{- range $key, $value :=  .Values.kibana.env }}
        - name: {{ $key | upper | replace "-" "_" }}
          value: {{ $value | quote }}
        {{- end }}
        resources:
{{ toYaml .Values.kibana.resources | indent 10 }}
        ports:
        - containerPort: 5601
          name: http
          protocol: TCP
        livenessProbe:
          exec:
            command:
              - pgrep
              - node
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: api/status
            port: http
            scheme: HTTPS
          initialDelaySeconds: 60
          timeoutSeconds: 5
        resources:
{{ toYaml .Values.kibana.resources | indent 10 }}
        volumeMounts:
        - mountPath: /usr/share/kibana/config/kibana.yml
          name: config
          subPath: kibana.yml
        - name: certificates-secrets-volume
          readOnly: true
          mountPath: "/usr/share/kibana/config/certificates-secrets"
      volumes:
        - name: certificates-secrets-volume
          secret:
            secretName: {{ template "fullname" . }}-nodes-cert-secret
            defaultMode: 0600
        - configMap:
            name: {{ template "fullname" . }}-kibana-config
          name: config
        - name: kubectl
          emptyDir: {}
{{ end }}