## Search Guard FLX 4 and Elasticsearch 8

common:
  ## Elasticsearch and Kibana version
  ## See what's available: https://hub.docker.com/r/floragunncom/sg-elasticsearch/tags
  elkversion: "8.19.18"

  ## Search Guard plugin version
  sgversion: "4.1.2"

  ## Search Guard Kibana plugin version
  ## See what's available: https://hub.docker.com/r/floragunncom/sg-kibana/tags
  sgkibanaversion: "4.1.2"

  sgctl_version: 4.1.2