{{- /*
    Copyright 2021 floragunn GmbH

    Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/}}

apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ template "searchguard.fullname" . }}-cleanup-sg-data"
  labels:
    app: {{ template "searchguard.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    role: sgadmin
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{ template "searchguard.fullname" . }}-cleanup-sg-data"
      labels:
        release: "{{ .Release.Name }}"
        app: {{ template "searchguard.fullname" . }}
        component: {{ template "searchguard.fullname" . }}
        role: sgadmin
    spec:
      restartPolicy: Never
      serviceAccountName: {{ template "searchguard.fullname" . }}
      containers:
        - name: cleanup-sg-data
          image: {{ .Values.common.images.repository }}/bitnami/kubectl:1.19
          resources:
                limits:
                  cpu: "500m"
                  memory: 256Mi
                requests:
                  cpu: 100m
                  memory: 256Mi
          imagePullPolicy: {{ .Values.common.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - |
{{ if .Values.common.remove_pvc_on_delete }}
                kubectl --namespace {{ .Release.Namespace }} delete $$(kubectl --namespace {{ .Release.Namespace }} get pvc -l component={{ template "searchguard.fullname" . }} -o name)
{{ end }}
                kubectl --namespace {{ .Release.Namespace }} delete secrets "{{ .Release.Name }}"-ingress-nginx-admission

                kubectl --namespace {{ .Release.Namespace }} delete $$(kubectl --namespace {{ .Release.Namespace }} get secrets -l app={{ template "searchguard.fullname" . }} -o name)