{{- /*
    Includes code from the following Apache 2 licensed projects:

      - https://github.com/lalamove/helm-elasticsearch

        Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/}}



{{- $dataValues := .Values.data }} 
{{- if not (kindIs "slice" .Values.data) }}
{{- $dataValues = list (merge (dict "name" "data") .Values.data) }}
{{- end }}

{{- range $dataValues  }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "searchguard.fullname" $ }}-{{ if eq .name "data" }}data{{ else }}data-{{ .name }}{{ end }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ template "searchguard.fullname" $ }}
    chart: "{{ $.Chart.Name }}"
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
    component: {{ template "searchguard.fullname" $ }}
    role: data
spec:
  serviceName: {{ template "searchguard.fullname" $ }}-{{ .name }}
  replicas: {{ .replicas }}
  updateStrategy:
    type: OnDelete
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      component: {{ template "searchguard.fullname" $ }}
      role: data
  template:
    metadata:
      labels:
        release: "{{ $.Release.Name }}"
        app: {{ template "searchguard.fullname" $ }}
        component: {{ template "searchguard.fullname" $ }}
        role: data
        estype: node
        {{- if .labels }}
{{ toYaml .labels | indent 8 }}
        {{- end }}
      annotations:
        {{ if $.Values.common.restart_pods_on_config_change }}
        checksum/config: {{ include (print $.Template.BasePath "/sg-static-configuration.yaml") $ | sha256sum }}
        {{ end }}
      {{- if .annotations }}
{{ toYaml .annotations | indent 8 }}
      {{- end }}
    spec:
      subdomain: {{ template "searchguard.fullname" $ }}
      serviceAccountName: {{ template "searchguard.fullname" $ }}
      securityContext:
        fsGroup: 1000
      {{ if or .nodeAffinity .antiAffinity }}
      affinity:
      {{ if .nodeAffinity }}
        nodeAffinity:
{{ toYaml .nodeAffinity | indent 10 }}
      {{ end }}     
      {{ end }}    
      {{- if eq .antiAffinity "hard" }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  component: {{ template "searchguard.fullname" $ }}
                  role: data
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: "topology.kubernetes.io/zone"
              labelSelector:
                matchLabels:
                  component: {{ template "searchguard.fullname" $ }}
                  role: data
      {{- else if eq .antiAffinity "soft" }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: "topology.kubernetes.io/zone"
              labelSelector:
                matchLabels:
                  component: {{ template "searchguard.fullname" $ }}
                  role: data
          - weight: 2
            podAffinityTerm:
              topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  component: {{ template "searchguard.fullname" $ }}
                  role: data
      {{- end }}
      {{ if .tolerations }}
      tolerations:
{{ toYaml .data.tolerations | indent 6 }}
      {{ end }}
      initContainers:  
{{ include "searchguard.init-containers" $ | indent 6 }}
      {{ if $.Values.common.docker_registry.enabled }}
      imagePullSecrets:
      - name: {{ $.Values.common.docker_registry.imagePullSecret }}
      {{ end }}
      containers:
      - name: elasticsearch
      {{ if $.Values.common.xpack_basic }}
        image: "{{ $.Values.common.images.repository }}/{{ $.Values.common.images.provider }}/{{ $.Values.common.images.elasticsearch_base_image }}:{{ $.Values.common.elkversion }}-{{ $.Values.common.sgversion }}"
      {{ else }}
        image: "{{ $.Values.common.images.repository }}/{{ $.Values.common.images.provider }}/{{ $.Values.common.images.elasticsearch_base_image }}:{{ $.Values.common.elkversion }}-oss-{{ $.Values.common.sgversion }}"
      {{ end }}
        imagePullPolicy: {{ $.Values.common.pullPolicy }}
        lifecycle:
          postStart:
{{ include "searchguard.remove-demo-certs" $ | indent 12 }}
{{ include "searchguard.recreate-node-certificates" $ | indent 20 }}

                    function try_loop {
                        for (( c=1; c<=100; c++ )); do \
                            eval $@ && exit_code=0 && break || exit_code=$? && echo "Retry $c in 5s" && \
                            sleep 5; \
                            done; \
                            (exit $exit_code)
                    }

                    
                    try_loop nc -z $DISCOVERY_SERVICE 9300
                    try_loop nc -z $DISCOVERY_SERVICE 9200
                    
                    curl --cert /sgcerts/crt.pem --key /sgcerts/key.pem --cacert /sgcerts/root-ca.pem "https://$DISCOVERY_SERVICE:9200/_cluster/health?wait_for_status=yellow&timeout=300s&pretty" > /tmp/poststart 2>&1 || true

                    try_loop nc -z $HOSTNAME 9200

                    curl --cert /sgcerts/crt.pem --key /sgcerts/key.pem --cacert /sgcerts/root-ca.pem -X PUT "https://$HOSTNAME:9200/_cluster/settings?pretty" -H 'Content-Type: application/json' -d'
                    {
                      "persistent": {
                        "cluster.routing.allocation.enable": null
                      }
                    }
                    ' >> /tmp/poststart 2>&1 || true

          preStop:
{{ include "searchguard.lifecycle-cleanup-certs" $ | indent 12 }}

                    curl -Ss --cert /sgcerts/crt.pem --key /sgcerts/key.pem --cacert /sgcerts/root-ca.pem -X PUT "https://$HOSTNAME:9200/_cluster/settings?pretty" -H 'Content-Type: application/json' -d'
                    {
                      "persistent": {
                        "cluster.routing.allocation.enable": "primaries"
                      }
                    }
                    ' #>> "/storage/prestop/$HOSTNAME" 2>&1 || true

                    curl -Ss --cert /sgcerts/crt.pem --key /sgcerts/key.pem --cacert /sgcerts/root-ca.pem -X POST "https://$HOSTNAME:9200/_flush/synced?pretty" #>> "/storage/prestop/$HOSTNAME" 2>&1 || true

{{ include "searchguard.security-context.least" $ | indent 8 }}
        envFrom:
        - secretRef:
            name: {{ template "searchguard.fullname" $ }}-passwd-secret
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: DISCOVERY_SERVICE
          value: {{ template "searchguard.fullname" $ }}-discovery.{{ $.Release.Namespace }}.svc
        - name: ES_JAVA_OPTS
          value: "-Djava.net.preferIPv4Stack=true -Xms{{ .heapSize }} -Xmx{{ .heapSize }}"
{{- if eq (include "searchguard.elk-version" $) "7" }}
        - name: NODE_DATA
          value: "true"
        - name: NODE_MASTER
          value: "false"
        - name: NODE_INGEST
          value: "false"
{{- else }}
        - name: NODE_ROLES
          value: "{{ join "," .roles }}"
{{- end }}
        - name: PROCESSORS
          value: "{{ .processors }}"
        {{- range $key, $value :=  $.Values.common.env }}
        - name: {{ $key | upper | replace "-" "_" }}
          value: {{ $value | quote }}
        {{- end }}
        {{- range $key, $value :=  .env }}
        - name: {{ $key | upper | replace "-" "_" }}
          value: {{ $value | quote }}
        {{- end }}
        ports:
        - containerPort: 9300
          name: transport
          protocol: TCP
        - containerPort: 9200
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /_searchguard/health
            port: http
            scheme: HTTPS
          initialDelaySeconds: 20
          periodSeconds: 10
          failureThreshold: 30
        livenessProbe:
          tcpSocket:
            port: transport
          initialDelaySeconds: 120
          periodSeconds: 10
        resources:
{{ toYaml .resources | indent 10 }}
        volumeMounts:
{{- include "searchguard.config-volume-mount" $ | nindent 8 }}          
        - mountPath: /usr/share/elasticsearch/data
          name: storage
          subPath: data
        - mountPath: /usr/share/elasticsearch/logs
          name: storage
          subPath: logs
        - mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          name: config
          subPath: elasticsearch.yml
        - name: secret-volume
          readOnly: true
          mountPath: "/usr/share/elasticsearch/config/certificates-secrets"
        - name: kubectl
          subPath: kubectl
          mountPath: /usr/local/bin/kubectl
          readOnly: true
        - name: secret-volume-admin-cert
          readOnly: true
          mountPath: /sgcerts/
        - name: nodes-cert
          mountPath: /sg-nodes-certs
          readOnly: true
{{ if $.Values.common.custom_elasticsearch_keystore.enabled }}
{{ include "searchguard.custom-elasticsearch-keystore-volumeMounts" . | indent 8 }}
{{ end }}
      volumes:
{{- include "searchguard.config-volumes" $ | nindent 8 }}             
        - name: secret-volume
          secret:
            secretName: {{ template "searchguard.fullname" $ }}-nodes-cert-secret
            defaultMode: 0644
        - configMap:
            name: {{ template "searchguard.fullname" $ }}-config
          name: config
        - name: kubectl
          emptyDir: {}
        - name: secret-volume-admin-cert
          secret:
            secretName: {{ template "searchguard.fullname" $ }}-admin-cert-secret
        - name: nodes-cert
          emptyDir: {}
{{ if $.Values.common.custom_elasticsearch_keystore.enabled }}
        - name: elasticsearch-keystore
          emptyDir: {}
{{ end }}
  volumeClaimTemplates:
  - metadata:
      name: storage 
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .storageClass }}
      resources:
        requests:
          storage: {{ .storage }}
{{- end }}