{{- /*
    Copyright 2021 floragunn GmbH

    Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/}}

{{ if .Values.common.ingressNginx.enabled }}
apiVersion: {{ template "searchguard.networking.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ template "searchguard.fullname" . }}-ingress-nginx
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  tls:
{{ if not (eq .Values.common.ingressNginx.ingressKibanaDomain "none") }}
    - hosts:
      - {{ .Values.common.ingressNginx.ingressKibanaDomain }}
      # This secret must exist beforehand
      # The cert must also contain the subj-name foo.bar.com
      # https://github.com/kubernetes/ingress-nginx/blob/master/docs/examples/PREREQUISITES.md#tls-certificates
      secretName: {{ template "searchguard.fullname" . }}-kibana-service-cert-secret
{{ end }}
{{ if not (eq .Values.common.ingressNginx.ingressElasticsearchDomain "none") }}
    - hosts:
      - {{ .Values.common.ingressNginx.ingressElasticsearchDomain }}
    # This secret must exist beforehand
    # The cert must also contain the subj-name bar.baz.com
    # https://github.com/kubernetes/ingress-nginx/blob/master/docs/examples/PREREQUISITES.md#tls-certificates
      secretName: {{ template "searchguard.fullname" . }}-es-service-cert-secret
{{ end }}
  rules:
{{ if not (eq .Values.common.ingressNginx.ingressKibanaDomain "none") }}
    - host: {{ .Values.common.ingressNginx.ingressKibanaDomain }}
      http:
        paths:
{{ if semverCompare "<1.19-0" .Capabilities.KubeVersion.GitVersion }}
          - backend:
              serviceName: {{ template "searchguard.fullname" . }}
              servicePort: 5601
            path: /
{{ else }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ template "searchguard.fullname" . }}
                port:
                  number: 5601
{{ end }}
{{ end }}
{{ if not (eq .Values.common.ingressNginx.ingressElasticsearchDomain "none") }}
    - host: {{ .Values.common.ingressNginx.ingressElasticsearchDomain }}
      http:
        paths:
  {{ if semverCompare "<1.19-0" .Capabilities.KubeVersion.GitVersion }}
          - backend:
              serviceName: {{ template "searchguard.fullname" . }}-clients
              servicePort: 9200
            path: /
  {{ else }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ template "searchguard.fullname" . }}-clients
                port:
                  number: 9200
  {{ end }}
{{ end }}
{{ end }}
