apiVersion: v1
kind: Service
metadata:
  name: {{ template "searchguard.fullname" . }}
  labels:
    app: {{ template "searchguard.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: {{ template "searchguard.fullname" . }}
    role: kibana
spec:
  type: {{ .Values.kibana.serviceType }}
  selector:
    component: {{ template "searchguard.fullname" . }}
    role: kibana
  ports:
  - name: http
    port: {{ .Values.kibana.httpPort }}
    targetPort: 5601
    protocol: TCP

