{{- /*
    Copyright 2021 floragunn GmbH

    Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/}}


{{- $kibanaValues := .Values.kibana }} 
{{- if not (kindIs "slice" .Values.kibana) }}
{{- $kibanaValues = list (merge (dict "name" "kibana") .Values.kibana) }}
{{- end }}

{{- range (slice $kibanaValues 0 1) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "searchguard.fullname" $ }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ template "searchguard.fullname" $ }}
    chart: "{{ $.Chart.Name }}"
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
    component: {{ template "searchguard.fullname" $ }}
    role: kibana
  {{ if and .service_annotations (eq .serviceType "LoadBalancer")}}
  annotations:
    {{- .service_annotations | toYaml | nindent 4 }}
  {{ end }}

spec:
  type: {{ .serviceType }}
{{ if and .loadBalancerIp (eq .serviceType "LoadBalancer") }}
  loadBalancerIP: {{ .loadBalancerIp }}
{{ end }} 
  selector:
    component: {{ template "searchguard.fullname" $ }}
    role: kibana
  ports:
  - name: http
    port: {{.httpPort }}
    targetPort: 5601
    protocol: TCP
    {{ if and .nodePort (eq .serviceType "NodePort") }}
    nodePort: {{ .nodePort }}
    {{ end }}

{{ end }}  