{{- /*
    Includes code from the following Apache 2 licensed projects:

      - https://github.com/lalamove/helm-elasticsearch

        Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/}}

{{- $masterValues := .Values.master }} 
{{- if not (kindIs "slice" .Values.master) }}
{{- $masterValues = list (merge (dict "name" "master") .Values.master) }}
{{- end }}

{{- range $masterValues  }}

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "searchguard.fullname" $ }}-{{ if eq .name "master" }}master{{ else }}master-{{ .name }}{{ end }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ template "searchguard.fullname" $ }}
    chart: "{{ $.Chart.Name }}"
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
    component: {{ template "searchguard.fullname" $ }}-master
    role: master
spec:
  serviceName: {{ template "searchguard.fullname" $ }}-master
  replicas: {{ .replicas }}
  updateStrategy:
    type: OnDelete
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      component: {{ template "searchguard.fullname" $ }}
      role: master
  template:
    metadata:
      labels:
        release: "{{ $.Release.Name }}"
        app: {{ template "searchguard.fullname" $ }}
        component: {{ template "searchguard.fullname" $ }}
        role: master
        estype: node
        {{- if .labels }}
{{ toYaml .labels | indent 8 }}
        {{- end }}
      annotations:
        {{ if $.Values.common.restart_pods_on_config_change }}
        checksum/config: {{ include (print $.Template.BasePath "/sg-static-configuration.yaml") $  | sha256sum }}
        {{ end }}
      {{- if .annotations }}
{{ toYaml .annotations | indent 8 }}
      {{- end }}
    spec:
      subdomain: {{ template "searchguard.fullname" $ }}
      serviceAccountName: {{ template "searchguard.fullname" $ }}
      securityContext:
        fsGroup: 1000
      {{ if or .nodeAffinity .antiAffinity }}
      affinity:
      {{ if .nodeAffinity }}
        nodeAffinity:
{{ toYaml .nodeAffinity | indent 10 }}
      {{ end }}     
      {{ end }}    
      {{- if eq .antiAffinity "hard" }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: "topology.kubernetes.io/zone"
              labelSelector:
                matchLabels:
                  component: {{ template "searchguard.fullname" $ }}
                  role: master
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  component: {{ template "searchguard.fullname" $ }}
                  role: master
      {{- else if eq .antiAffinity "soft" }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: "topology.kubernetes.io/zone"
              labelSelector:
                matchLabels:
                  component: {{ template "searchguard.fullname" $ }}
                  role: master
          - weight: 2
            podAffinityTerm:
              topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchLabels:
                  component: {{ template "searchguard.fullname" $ }}
                  role: master
      {{- end }}
      {{ if .tolerations }}
      tolerations:
{{ toYaml .tolerations | indent 6 }}
      {{ end }}
      initContainers:
{{ include "searchguard.init-containers" $ | indent 6 }}
      {{ if $.Values.common.docker_registry.enabled }}
      imagePullSecrets:
      - name: {{ .Values.common.docker_registry.imagePullSecret }}
      {{ end }}
      containers:
      - name: elasticsearch
{{ include "searchguard.security-context.least" $ | indent 8 }}
      {{ if $.Values.common.xpack_basic }}
        image: "{{ $.Values.common.images.repository }}/{{ $.Values.common.images.provider }}/{{ $.Values.common.images.elasticsearch_base_image }}:{{ $.Values.common.elkversion }}-{{ $.Values.common.sgversion }}"
      {{ else }}
        image: "{{ $.Values.common.images.repository }}/{{ $.Values.common.images.provider }}/{{ $.Values.common.images.elasticsearch_base_image }}:{{ $.Values.common.elkversion }}-oss-{{ $.Values.common.sgversion }}"
      {{ end }}
        imagePullPolicy: {{ $.Values.common.pullPolicy }} 
        lifecycle:
          postStart:
{{ include "searchguard.remove-demo-certs" $ | indent 12 }}
{{ include "searchguard.recreate-node-certificates" $ | indent 20 }}
          preStop:
{{ include "searchguard.lifecycle-cleanup-certs" $ | indent 12 }}
        envFrom:
        - secretRef:
            name: {{ template "searchguard.fullname" $ }}-passwd-secret
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: DISCOVERY_SERVICE
          value: {{ template "searchguard.fullname" $ }}-discovery.{{ $.Release.Namespace }}.svc
        - name: ES_JAVA_OPTS
          value: "-Djava.net.preferIPv4Stack=true -Xms{{ .heapSize }} -Xmx{{ .heapSize }}"
        - name: NODE_ROLES
          value: "{{ join "," .roles }}"
        - name: PROCESSORS
          value: "{{ .processors }}"

        {{ if or $.Release.IsInstall (not $.Values.common.remove_initial_master_nodes_after_install) }}
        {{- $master_name := printf "%s-%s" (include "searchguard.fullname" $) "master" }}
        {{- $zkservers := list -}}
        {{- range $ordinal, $e := untilStep 0 (.replicas | int) 1 }}
        {{- $zkservers = printf "%s-%d" $master_name $ordinal | append $zkservers -}}
        {{- end -}}

        - name: "cluster.initial_master_nodes"
          value: {{ join "," $zkservers | quote }}

        {{- end }}


        {{- range $key, $value :=  $.Values.common.env }}
        - name: {{ $key | upper | replace "-" "_" }}
          value: {{ $value | quote }}
        {{- end }}
        {{- range $key, $value :=  .env }}
        - name: {{ $key | upper | replace "-" "_" }}
          value: {{ $value | quote }}
        {{- end }}
        ports:
        - containerPort: 9300
          name: transport
          protocol: TCP
        - containerPort: 9200
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /_searchguard/health?mode=nonstrict
            port: http
            scheme: HTTPS
          initialDelaySeconds: 20
          timeoutSeconds: 10
          failureThreshold: 30
        livenessProbe:
          tcpSocket:
            port: transport
          initialDelaySeconds: 120
          periodSeconds: 10
        startupProbe:
          httpGet:
            path: /_searchguard/health?mode=nonstrict
            port: http
            scheme: HTTPS
          initialDelaySeconds: 10
          periodSeconds: 15
          failureThreshold: 40          
        resources:
{{ toYaml .resources | indent 10 }}
        volumeMounts:
{{- include "searchguard.config-volume-mount" . | nindent 8 }}          
        - mountPath: /usr/share/elasticsearch/data
          name: storage
          subPath: data
        - mountPath: /usr/share/elasticsearch/logs
          name: storage
          subPath: logs
        - mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          name: config
          subPath: elasticsearch.yml
        - name: secret-volume
          readOnly: true
          mountPath: "/usr/share/elasticsearch/config/certificates-secrets"
        - name: kubectl
          subPath: kubectl
          mountPath: /usr/local/bin/kubectl
          readOnly: true
        - name: nodes-cert
          mountPath: /sg-nodes-certs
          readOnly: true
{{ if $.Values.common.custom_elasticsearch_keystore.enabled }}
{{ include "searchguard.custom-elasticsearch-keystore-volumeMounts" . | indent 8 }}
{{ end }}
      volumes:
{{- include "searchguard.config-volumes" $ | nindent 8 }}    
        - name: secret-volume
          secret:
            secretName: {{ template "searchguard.fullname" $ }}-nodes-cert-secret
            defaultMode: 0644
        - configMap:
            name: {{ template "searchguard.fullname" $ }}-config
          name: config
        - name: kubectl
          emptyDir: {}
        - name: nodes-cert
          emptyDir: {}
{{ if $.Values.common.custom_elasticsearch_keystore.enabled }}
        - name: elasticsearch-keystore
          emptyDir: {}
{{ end }}
  volumeClaimTemplates:
  - metadata:
      name: storage   
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .storageClass }}
      resources:
        requests:
          storage: {{ .storage }}
{{- end }}     