---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "searchguard.fullname" . }}-sg-role
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "searchguard.fullname" . }}
    chart: "{{ .Chart.Name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-6"
rules:
    #"get","list", "watch"
  - apiGroups: ["","apps","batch"]
    resources: ["pods","persistentvolumes","persistentvolumeclaims","configmaps","services","secrets","statefulsets","controllerrevisions","jobs","statefulsets/scale"]
    verbs: ["get","list", "watch"]
    
    #"delete"
  - apiGroups: ["","batch"]
    resources: ["pods","persistentvolumeclaims","secrets","jobs"]
    verbs: ["delete"]

    #create, patch
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create","patch"]

    #patch (scaling)
  - apiGroups: ["apps"]
    resources: ["statefulsets","statefulsets/scale"]
    verbs: ["patch"]
