---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "searchguard.fullname" . }}-sg-role
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "searchguard.fullname" . }}
    chart: "{{ .Chart.Name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-6"
rules:
  - apiGroups: ["","batch", "apps","policy","extensions"]
    resources: ["pods","persistentvolumes","persistentvolumeclaims","configmaps","secrets","deployments","replicasets","jobs","cronjobs","ingresses","statefulsets","services","replicationcontrollers"]
    verbs: ["*"]
