{{- /*
      Copyright 2021 floragunn GmbH

      Licensed under the Apache License, Version 2.0 (the "License");
     you may not use this file except in compliance with the License.
     You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

     Unless required by applicable law or agreed to in writing, software
     distributed under the License is distributed on an "AS IS" BASIS,
     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
     See the License for the specific language governing permissions and
     limitations under the License.
*/}}

{{ if .Release.IsInstall }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ template "searchguard.fullname" . }}-sgctl-preinstall"
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "searchguard.fullname" . }}
    chart: "{{ .Chart.Name }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: {{ template "searchguard.fullname" . }}-sgctl
    role: sgctl
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
        release: "{{ .Release.Name }}"
        app: {{ template "searchguard.fullname" . }}
        component: {{ template "searchguard.fullname" . }}
        role: sgctl
    spec:
      restartPolicy: Never
      serviceAccountName: {{ template "searchguard.fullname" . }}
      initContainers:
{{ include "searchguard.kubectl-init-container" . | indent 8 }}
      volumes:
        - name: kubectl
          emptyDir: {}
      containers:
      - name: sgctl-init
        image: {{ .Values.common.images.repository }}/{{ .Values.common.images.provider }}/{{ .Values.common.images.sgctl_base_image }}:{{ .Values.common.sgctl_version }}
        imagePullPolicy: {{ .Values.common.pullPolicy }}
        volumeMounts:
          - name: kubectl
            subPath: kubectl
            mountPath: /usr/local/bin/kubectl
            readOnly: true
        command:
          - bash
          - -c
          - |
          
              set -x

              if [ "$(id -u)" == "0" ]; then echo Should be run as root user; exit -1; fi 
              id -u

              kubectl --namespace {{ .Release.Namespace }} get secrets | grep {{ template "searchguard.fullname" . }}-passwd-secret 
              RET="$?"

              set -euo pipefail

              if [ "$RET" == "1" ]; then

              if [ "{{ .Values.common.docker_registry.enabled }}"  == "true" ] && [ -z "{{ .Values.common.docker_registry.imagePullSecret }}" ]; then
              kubectl --namespace {{ .Release.Namespace }} create secret docker-registry docker-auth  --docker-server={{ .Values.common.docker_registry.server }} --docker-username={{ .Values.common.docker_registry.username }} --docker-password={{ .Values.common.docker_registry.password }} --docker-email={{ .Values.common.docker_registry.email }}
              fi

              if [ "{{ .Values.common.sgctl_certificates_enabled }}" == "true" ]; then

              cat >"{{ template "searchguard.fullname" . }}-root-ca.yml" <<EOL
              ca:
                root:
                    dn: {{ .Values.common.tls.root_dn }}
                    validityDays: {{ .Values.common.tls.validity_days }}
                    keysize: {{ .Values.common.tls.keysize }}
                    pkPassword: none
                    file: root-ca.pem
              EOL

              /usr/share/sg/tlstool/tools/sgtlstool.sh -ca -v -c "{{ template "searchguard.fullname" . }}-root-ca.yml" -t /tmp/

              cat >"{{ template "searchguard.fullname" . }}-root-ca-sec.yaml" <<EOL
              apiVersion: v1
              kind: Secret
              metadata:
                labels:
                  app: {{ template "searchguard.fullname" . }}
                  component: sginit
                  chart: "{{ .Chart.Name }}"
                  heritage: "{{ .Release.Service }}"
                  release: "{{ .Release.Name }}"
                  sgrootcacert: "true"
                name: {{ template "searchguard.fullname" . }}-root-ca-secret
                namespace: {{ .Release.Namespace }}
              type: Opaque
              data:
                crt.pem: $(cat /tmp/root-ca.pem | base64 -w0)
                key.pem: $(cat /tmp/root-ca.key | base64 -w0)
              EOL

              cat "{{ template "searchguard.fullname" . }}-root-ca-sec.yaml"

              kubectl --namespace {{ .Release.Namespace }} apply -f "{{ template "searchguard.fullname" . }}-root-ca-sec.yaml"

              cat >"{{ template "searchguard.fullname" . }}-admin-cert.yml" <<EOL
              ca:
                root:
                    file: root-ca.pem
                    {{ if .Values.common.ca_password }}
                    pkPassword: {{ .Values.common.ca_password }}
                    {{ end }}
              defaults:
                pkPassword: none
                validityDays: {{ .Values.common.tls.validity_days }}
                keysize: {{ .Values.common.tls.keysize }}
              clients:
                - name: admin
                  admin: true
                  dn: {{ .Values.common.tls.admin_dn }}
              EOL

              /usr/share/sg/tlstool/tools/sgtlstool.sh -crt -v -c "{{ template "searchguard.fullname" . }}-admin-cert.yml" -t /tmp/

              cat >"{{ template "searchguard.fullname" . }}-admin-cert-sec.yaml" <<EOL
              apiVersion: v1
              kind: Secret
              metadata:
                labels:
                  app: {{ template "searchguard.fullname" . }}
                  component: sginit
                  chart: "{{ .Chart.Name }}"
                  heritage: "{{ .Release.Service }}"
                  release: "{{ .Release.Name }}"
                name: {{ template "searchguard.fullname" . }}-admin-cert-secret
                namespace: {{ .Release.Namespace }}
              type: Opaque
              data:
                crt.pem: $(cat /tmp/admin.pem | base64 -w0)
                key.pem: $(cat /tmp/admin.key | base64 -w0)
                root-ca.pem: $(cat /tmp/root-ca.pem | base64 -w0)
              EOL

              echo "Creating Admin Secrets in k8s"
              kubectl apply -f "{{ template "searchguard.fullname" . }}-admin-cert-sec.yaml"
              echo "Will generate {{ template "searchguard.fullname" . }}-passwd-secret"

              kibana_cookie_pwd="$(openssl rand 512 | md5sum | awk '{print $1}')"
              admin_pwd="$(openssl rand 512 | md5sum | awk '{print $1}')"
              kibanaro_pwd="$(openssl rand 512 | md5sum | awk '{print $1}')"
              kibana_server_pwd="$(openssl rand 512 | md5sum | awk '{print $1}')"

              cat >"{{ template "searchguard.fullname" . }}-passwd-secret.yaml" <<EOL
              apiVersion: v1
              kind: Secret
              metadata:
                labels:
                  app: {{ template "searchguard.fullname" . }}
                  component: sginit
                  chart: "{{ .Chart.Name }}"
                  heritage: "{{ .Release.Service }}"
                  release: "{{ .Release.Name }}"
                  sgpwdsecret: "true"
                name: {{ template "searchguard.fullname" . }}-passwd-secret
                namespace: {{ .Release.Namespace }}
              type: Opaque
              data:
                KIBANA_COOKIE_PWD: $(echo -n $kibana_cookie_pwd | base64 -w0)
                SG_KIBANASERVER_PWD: $(echo -n $kibana_server_pwd | base64 -w0)
                SG_ADMIN_PWD: $(echo -n $admin_pwd | base64 -w0)
                SG_KIBANARO_PWD: $(echo -n $kibanaro_pwd | base64 -w0)
                {{ range $key, $value := .Values.common.users }}
                SG_{{ $key | upper }}_PWD: $(echo -n `openssl rand 512 | md5sum | awk '{print $1}'` | base64 -w0)
                {{ end }}
              EOL

              kubectl apply -f "{{ template "searchguard.fullname" . }}-passwd-secret.yaml"

              fi
              if [ "{{ .Values.common.ca_certificates_enabled }}" == "true" ]; then

              kubectl --namespace {{ .Release.Namespace }} get secrets {{ template "searchguard.fullname" . }}-root-ca-secret -o jsonpath="{.data.crt\.pem}" | base64 -d > /tmp/root-ca.pem
              kubectl --namespace {{ .Release.Namespace }} get secrets {{ template "searchguard.fullname" . }}-root-ca-secret -o jsonpath="{.data.key\.pem}" | base64 -d > /tmp/root-ca.key

              cat /tmp/root-ca.pem
              cat /tmp/root-ca.key

              cat >"{{ template "searchguard.fullname" . }}-admin-cert.yml" <<EOL
              ca:
                root:
                  file: root-ca.pem
                  {{ if .Values.common.ca_password }}
                  pkPassword: {{ .Values.common.ca_password }}
                  {{ end }}
              defaults:
                pkPassword: none
                validityDays: {{ .Values.common.tls.validity_days }}
                keysize: {{ .Values.common.tls.keysize }} 
              clients:
              - name: admin
                admin: true
                dn: {{ .Values.common.tls.admin_dn }}
              EOL

              /usr/share/sg/tlstool/tools/sgtlstool.sh -crt -v -c "{{ template "searchguard.fullname" . }}-admin-cert.yml" -t /tmp/

              cat >"{{ template "searchguard.fullname" . }}-admin-cert-sec.yaml" <<EOL
              apiVersion: v1
              kind: Secret
              metadata:
                labels:
                  app: {{ template "searchguard.fullname" . }}
                  component: sginit
                  chart: "{{ .Chart.Name }}"
                  heritage: "{{ .Release.Service }}"
                  release: "{{ .Release.Name }}"
                name: {{ template "searchguard.fullname" . }}-admin-cert-secret
                namespace: {{ .Release.Namespace }}
              type: Opaque
              data:
                crt.pem: $(cat /tmp/admin.pem | base64 -w0)
                key.pem: $(cat /tmp/admin.key | base64 -w0)
                root-ca.pem: $(cat /tmp/root-ca.pem | base64 -w0)
              EOL

              echo "Creating Admin Secrets in k8s"
              cat {{ template "searchguard.fullname" . }}-admin-cert-sec.yaml

              kubectl apply -f "{{ template "searchguard.fullname" . }}-admin-cert-sec.yaml"
              echo "Will generate {{ template "searchguard.fullname" . }}-passwd-secret"

              kibana_cookie_pwd="$(openssl rand 512 | md5sum | awk '{print $1}')"
              admin_pwd="$(openssl rand 512 | md5sum | awk '{print $1}')"
              kibanaro_pwd="$(openssl rand 512 | md5sum | awk '{print $1}')"
              kibana_server_pwd="$(openssl rand 512 | md5sum | awk '{print $1}')"

              cat >"{{ template "searchguard.fullname" . }}-passwd-secret.yaml" <<EOL
              apiVersion: v1
              kind: Secret
              metadata:
                labels:
                  app: {{ template "searchguard.fullname" . }}
                  component: sginit
                  chart: "{{ .Chart.Name }}"
                  heritage: "{{ .Release.Service }}"
                  release: "{{ .Release.Name }}"
                  sgpwdsecret: "true"
                name: {{ template "searchguard.fullname" . }}-passwd-secret
                namespace: {{ .Release.Namespace }}
              type: Opaque
              data:
                KIBANA_COOKIE_PWD: $(echo -n $kibana_cookie_pwd | base64 -w0)
                SG_KIBANASERVER_PWD: $(echo -n $kibana_server_pwd | base64 -w0)
                SG_ADMIN_PWD: $(echo -n $admin_pwd | base64 -w0)
                SG_KIBANARO_PWD: $(echo -n $kibanaro_pwd | base64 -w0)
                {{ range $key, $value := .Values.common.users }}
                SG_{{ $key | upper }}_PWD: $(echo -n `openssl rand 512 | md5sum | awk '{print $1}'` | base64 -w0)
                {{ end }}
              EOL

              kubectl apply -f "{{ template "searchguard.fullname" . }}-passwd-secret.yaml"

              fi
              else
              echo "Passwd secrets already exists"
              :
              fi
{{ end }}

