{{- /*
    Copyright 2021 floragunn GmbH

    Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/}}

---
{{ if .Values.common.external_ca_certificates_enabled }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "searchguard.fullname" . }}
    component: sginit
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ template "searchguard.fullname" . }}-admin-cert-secret
  namespace: "{{ .Release.Namespace }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-4"
data:
{{- $path := printf "%s/sgadmin/*.pem" .Values.common.certificates_directory }}
{{ tpl ((.Files.Glob $path).AsSecrets) . | indent 4 }}
{{ end }}
---
{{ if .Values.common.external_ca_certificates_enabled }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "searchguard.fullname" . }}
    component: sginit
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ template "searchguard.fullname" . }}-nodes-cert-secret
  namespace: "{{ .Release.Namespace }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-4"
data:
{{- $path := printf "%s/nodes/*" .Values.common.certificates_directory }}
{{ tpl ((.Files.Glob $path).AsSecrets) . | indent 4 }}
{{ end }}
---
{{ if and (eq .Values.common.ingressNginx.enabled true) (eq .Values.common.ingressNginx.ingressCertificates "external") }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "searchguard.fullname" . }}
    component: sginit
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ template "searchguard.fullname" . }}-kibana-service-cert-secret
  namespace: "{{ .Release.Namespace }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-4"
data:
{{- $path := printf "%s/ingress_certificates/kibana/*" .Values.common.certificates_directory }}
{{ tpl ((.Files.Glob $path).AsSecrets) . | indent 4 }}
{{ end }}
---
{{ if and (eq .Values.common.ingressNginx.enabled true) (eq .Values.common.ingressNginx.ingressCertificates "external") }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "searchguard.fullname" . }}
    component: sginit
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ template "searchguard.fullname" . }}-es-service-cert-secret
  namespace: "{{ .Release.Namespace }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-4"
data:
{{- $path := printf "%s/ingress_certificates/elasticsearch/*" .Values.common.certificates_directory }}
{{ tpl ((.Files.Glob $path).AsSecrets) . | indent 4 }}
{{ end }}
---
{{ if .Values.common.ca_certificates_enabled }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "searchguard.fullname" . }}
    component: sginit
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ template "searchguard.fullname" . }}-root-ca-secret
  namespace: "{{ .Release.Namespace }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-4"
data:
{{- $path := printf "%s/ca/*" .Values.common.certificates_directory }}
{{ tpl ((.Files.Glob $path).AsSecrets) . | indent 4 }}
{{ end }}
---
{{ if .Values.common.external_ca_single_certificate_enabled }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "searchguard.fullname" . }}
    component: sginit
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ template "searchguard.fullname" . }}-admin-cert-secret
  namespace: "{{ .Release.Namespace }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-4"
data:
{{- $path := printf "%s/sgadmin/*.pem" .Values.common.certificates_directory }}
{{ tpl ((.Files.Glob $path).AsSecrets) . | indent 4 }}
{{ end }}
---
{{ if .Values.common.external_ca_single_certificate_enabled }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "searchguard.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ template "searchguard.fullname" . }}-nodes-cert-secret
  namespace: "{{ .Release.Namespace }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-4"
data:
{{- $path := printf "%s/nodes/*" .Values.common.certificates_directory }}
{{ tpl ((.Files.Glob $path).AsSecrets) . | indent 4 }}
{{ end }}