common:

  # Configure additional users (maps to sg_internal_users.yml)
  # https://docs.search-guard.com/latest/first-steps-user-configuration
  users:
    demouser:
      hash: $2a$12$wtusE0WRlhmRhqQQccjaw.NuM7aWyhc29gM8LobXAU/XqOhYFa4x. 
      backend_roles:
        - beatsreader


  # Configure additional rolemappings (maps to sg_roles_mapping.yml)
  # https://docs.search-guard.com/latest/first-steps-mapping-users-roles
  rolesmapping:
    sg_read_beats:
      backend_roles:
        - beatsreader

  # Configure additional role (maps to sg_roles.yml)
  # https://docs.search-guard.com/latest/first-steps-roles-configuration
  roles:
    sg_read_beats:
      cluster_permissions:
        - SGS_CLUSTER_COMPOSITE_OPS_RO
      index_permissions:
        - index_patterns:
            - "*beat*"
          allowed_actions:
            - SGS_READ

